WINDOW_WIDTH = 256
WINDOW_HEIGHT = 256
FPS = 24
WINDOW_TITLE = "Goldrush"
CLS_COLOR = 0
FONT_CHAR_WIDTH = 4

SCENE_TITLE = "title"
SCENE_HOME = "home"
SCENE_CHARACTERS = "characters"
SCENE_STAGE_MAP = "stage_map"
SCENE_SETTINGS = "settings"

COLOR_TITLE = 10
COLOR_TEXT = 7

PROMPT_BLINK_INTERVAL = 60
